import { describe, it, expect } from 'vitest';
import app from '../../../../src/index';
import { generateCodeVerifier } from '../../../../src/services/oauth/pkce';
import { JWTService } from '../../../../src/services/oauth/jwt';
import { makeTestEnv } from '../../../helpers/env';

const form = (params: Record<string, string>) => ({
  method: 'POST',
  headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  body: new URLSearchParams(params).toString(),
});

describe('OAuth 2.1 Token Endpoint', () => {
  it('should reject an unknown authorization code (with PKCE present)', async () => {
    const codeVerifier = generateCodeVerifier();

    const res = await app.request(
      '/oauth/token',
      form({
        grant_type: 'authorization_code',
        code: 'auth_testcode123',
        redirect_uri: 'https://client.example.com/callback',
        client_id: 'test-client-id',
        code_verifier: codeVerifier,
      }),
      makeTestEnv()
    );

    expect(res.status).toBe(400);
    expect(await res.json()).toMatchObject({
      error: 'invalid_grant',
      error_description: 'Invalid or expired authorization code',
    });
  });

  it('should reject request without required content-type', async () => {
    const res = await app.request(
      '/oauth/token',
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ grant_type: 'authorization_code' }),
      },
      makeTestEnv()
    );

    expect(res.status).toBe(400);
    expect(await res.json()).toMatchObject({
      error: 'invalid_request',
      error_description: 'Content-Type must be application/x-www-form-urlencoded',
    });
  });

  it('should reject an unknown refresh token', async () => {
    const res = await app.request(
      '/oauth/token',
      form({
        grant_type: 'refresh_token',
        refresh_token: 'refresh_testtoken123',
        client_id: 'test-client-id',
      }),
      makeTestEnv()
    );

    expect(res.status).toBe(400);
    expect(await res.json()).toMatchObject({
      error: 'invalid_grant',
      error_description: 'Invalid or expired refresh token',
    });
  });

  it('should reject authorization code grant without code_verifier', async () => {
    const res = await app.request(
      '/oauth/token',
      form({
        grant_type: 'authorization_code',
        code: 'auth_testcode123',
        redirect_uri: 'https://client.example.com/callback',
        client_id: 'test-client-id',
      }),
      makeTestEnv()
    );

    expect(res.status).toBe(400);
    expect(await res.json()).toMatchObject({
      error: 'invalid_request',
      error_description: 'code_verifier is required for PKCE',
    });
  });

  it('should reject request with unsupported grant type', async () => {
    const res = await app.request(
      '/oauth/token',
      form({
        grant_type: 'client_credentials',
        client_id: 'test-client-id',
        client_secret: 'test-secret',
      }),
      makeTestEnv()
    );

    expect(res.status).toBe(400);
    expect(await res.json()).toMatchObject({
      error: 'unsupported_grant_type',
      error_description: "Grant type 'client_credentials' is not supported",
    });
  });

  it('should reject request without grant_type', async () => {
    const res = await app.request('/oauth/token', form({}), makeTestEnv());

    expect(res.status).toBe(400);
    expect(await res.json()).toMatchObject({
      error: 'invalid_request',
      error_description: 'Missing grant_type parameter',
    });
  });

  it('should properly validate JWT tokens generated by the system', async () => {
    const jwtService = new JWTService('test-secret-key', 'HS256', 'test-issuer');

    const token = await jwtService.createToken({
      issuer: 'test-issuer',
      subject: 'user123',
      audience: 'client123',
      scopes: 'read write',
      expiresIn: 3600,
      tenantId: 'tenant123',
      userId: 'user123',
      resourceIndicators: ['resource1'],
      mcpPermissions: ['read', 'write'],
    });

    const result = await jwtService.verifyToken(token);

    expect(result.payload.sub).toBe('user123');
    expect(result.payload.aud).toBe('client123');
    expect(result.payload.scope).toBe('read write');
    expect((result.payload as any).tenant_id).toBe('tenant123');
    expect((result.payload as any).user_id).toBe('user123');
  });
});
